BeestjeOpJeFeestje/BeestjeOpJeFeestje/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BeestjeOpJeFeestje.Models.CustomValidation;

namespace BeestjeOpJeFeestje.Models
{
	public class Booking
	{
        //TODO: AnimalAccesories weghalen en Animals een 1 op meer relatie laten hebben met accesories! (Een beestje mag meerder accesories hebben)
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int ID { get; set; }

		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		[DataType(DataType.Date), DateIsNotBooked]
		public DateTime Date { get; set; }


		public Booking()
		{

		}

		public List<BookingAnimal> BookingAnimals { get; set; }
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Models/BookingModel/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BeestjeOpJeFeestje.Models.CustomValidation;

namespace BeestjeOpJeFeestje.Models
{
	public class Booking
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int ID { get; set; }

		[DateIsNotInThePast]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		[DataType(DataType.Date)]
		public DateTime Date { get; set; }
		
		[DisplayFormat(DataFormatString = "{0:n} €"), Display(Name = "Total Price")]
        public double TotalPrice { get; set; }

        [Display(Name = "Booked Animals")]
        public List<BookingAnimal> BookingAnimals { get; set; }
        [Display(Name = "Booked Accessories")]
		public List<BookingAccessories> BookingAccessories { get; set; }

        [Display(Name = "Client ID")]
		public int ClientInfoId { get; set; }
        [Display(Name = "Client")]
		public ClientInfo ClientInfo { get; set; }

		[NotMapped] public BookingState BookingState { get; set; } = BookingState.Animals;

		public Booking()
		{
		}


	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Controllers/BookingsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BeestjeOpJeFeestje.Models;
using BeestjeOpJeFeestje.Models.Repositories;
using BeestjeOpJeFeestje.Models.Validators;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace BeestjeOpJeFeestje.Controllers
{
	public class BookingsController : Controller
	{
		private readonly IRepository<Booking> _bookingRepository;
		private readonly IRepository<Animal> _animalRepository;
		private readonly IRepository<BookingProcess> _bookingProcessRepository;

		public BookingsController(IRepository<Booking> bookingRepository, IRepository<Animal> animalRepository, IRepository<BookingProcess> bookingProcessRepository)
		{
			_bookingRepository = bookingRepository;
			_animalRepository = animalRepository;
			_bookingProcessRepository = bookingProcessRepository;
		}

		// GET: Bookings/Edit/5
		public async Task<IActionResult> AnimalSelection(Booking booking)
		{
			Booking foundBooking = await ((BookingDBRepository) _bookingRepository).GetFromDate(booking.Date);
			if (foundBooking != null)
			{
				booking = foundBooking;
			}

			BookingProcess bookingProcess = new BookingProcess()
			{
				Booking = booking
			};

			return View(bookingProcess);
		}



		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AnimalsSelected(BookingProcess data)
		{
			AnimalSelectionValidator animalSelectionValidator = new AnimalSelectionValidator();

			Booking booking = await ((BookingDBRepository) _bookingRepository).GetFromDate(data.Booking.Date);
			List<Animal> selectedAnimals = new List<Animal>();
			foreach (Animal animal in data.Animals)
			{
				if (booking != null && animal.BookingIsSelected)
				{
					if (animalSelectionValidator.IsAnimalAlreadyBooked(booking.BookingAnimals, animal.ID))
					{
						TempData["error"] = "Selected animals are already booked";
						return RedirectToActionPermanent(nameof(AnimalSelection), booking);
					}
				}

				if(animal.BookingIsSelected)
				{
					Animal dAnimal = await ((AnimalDbRepository) _animalRepository).Get(animal.ID);
					selectedAnimals.Add(dAnimal);
				}
			}

			booking = data.Booking;
			if (!animalSelectionValidator.IsAnAnimalSelected(selectedAnimals))
			{
				TempData["error"] = "Please select an animal";
				return RedirectToActionPermanent(nameof(AnimalSelection), booking);
			}

			if (!animalSelectionValidator.FarmAnimalHasNoLionOrIceBear(selectedAnimals))
			{
				TempData["error"] = "An animal from the farm can not be along with Lion and Ice Bear";
				return RedirectToActionPermanent(nameof(AnimalSelection), booking);
			}

			if (animalSelectionValidator.PenguinIsHiredInWeekend(selectedAnimals, data.Booking.Date))
			{
				TempData["error"] = "Penguin can not be booked during the weekend";
				return RedirectToActionPermanent(nameof(AnimalSelection), booking);
			}

			if (animalSelectionValidator.DesertAnimalIsHiredInWinter(selectedAnimals, data.Booking.Date))
			{
				TempData["error"] = "Desert animal can not be selected for the Winter";
				return RedirectToActionPermanent(nameof(AnimalSelection), booking);
			}

			if (animalSelectionValidator.SnowAnimalIsHiredForSummer(selectedAnimals, data.Booking.Date))
			{
				TempData["error"] = "Snow Animal cannot be selected for the Summer";
				return RedirectToActionPermanent(nameof(AnimalSelection), booking);
			}

			data.DateTime = data.Booking.Date;
			data.Animals = selectedAnimals;
			data.Booking.BookingState = BookingState.Accessories;
			return View("AnimalSelection", data);
		}

		public async Task<IActionResult> AccessoriesSelected(BookingProcess data)
		{
			List<Accessories> accessories = new List<Accessories>();
			if (data.Accessories != null)
			{
				foreach (Accessories dataAccessory in data.Accessories)
				{
					if (dataAccessory.BookingIsSelected)
					{
						accessories.Add(dataAccessory);
					}
				}
			}
			

			data.Accessories = accessories;
			data.Booking.BookingState = BookingState.Details;
			return View("AnimalSelection", data);
		}

		public IActionResult PersonalInformation(BookingProcess data)
		{
			data.Booking.BookingState = BookingState.Confirmation;
			return View("AnimalSelection", data);
		}

		public async Task<IActionResult> ConfirmBooking(BookingProcess data)
		{
			BookingProcess bookingProcess = await _bookingProcessRepository.Get(data.ID);
			Booking booking = new Booking
			{
				BookingAccessories = new List<BookingAccessories>(),
				BookingAnimals = new List<BookingAnimal>(),
				ClientInfoId = bookingProcess.ClientInfoId,
				TotalPrice = bookingProcess.TotalPrice,
				Date = bookingProcess.DateTime
			};

			foreach (BookingProcessAccessories bpAccessories in bookingProcess.BookingProcessAccessories)
			{
				booking.BookingAccessories.Add(new BookingAccessories()
				{
					AccessoriesId = bpAccessories.AccessoriesId
				});
			}
			foreach (BookingProcessAnimal bpAnimal in bookingProcess.BookingProcessAnimals)
			{
				booking.BookingAnimals.Add(new BookingAnimal()
				{
					AnimalId = bpAnimal.AnimalId
				});
			}

			await _bookingRepository.Create(booking);
			return RedirectToActionPermanent(nameof(HomeController.Index), "Home");
		}

		public async Task<IActionResult> Index()
		{
			return View(await _bookingRepository.GetAll());
		}

		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Booking booking = await _bookingRepository.Get(id);
			if (booking == null)
			{
				return NotFound();
			}

			return View(booking);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Booking booking = await _bookingRepository.Get(id);
			if (booking == null)
			{
				return NotFound();
			}

			return View(booking);
		}

		// POST: Accessories/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			Booking booking = await _bookingRepository.Get(id);
			await _bookingRepository.Delete(booking);
			return RedirectToAction(nameof(Index));
		}
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/ViewComponents/AnimalSelectionViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using BeestjeOpJeFeestje.Models;
using BeestjeOpJeFeestje.Models.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.ViewComponents
{
	public class AnimalSelectionViewComponent : ViewComponent
	{
		private readonly AnimalDbRepository _repository;

		public AnimalSelectionViewComponent(IRepository<Animal> repository)
		{
			_repository = (AnimalDbRepository) repository;
		}

		public async Task<IViewComponentResult> InvokeAsync(BookingProcess data)
		{
			List<Animal> animals = await _repository.GetAll();

			if (data.Booking.BookingAnimals != null)
			{
				foreach (BookingAnimal bookingBookingAnimal in data.Booking.BookingAnimals)
				{
					foreach (Animal animal in animals)
					{
						if (animal.ID == bookingBookingAnimal.AnimalId)
						{
							animal.Booked = true;
						}
					}
				}
			}
			
			

			data.Animals = animals;
			return View(data);
		}
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/ViewComponents/BookingDetailViewComponent.cs
using System.Threading.Tasks;
using BeestjeOpJeFeestje.Models;
using BeestjeOpJeFeestje.Models.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.ViewComponents
{
	public class BookingDetailViewComponent : ViewComponent
	{
		private readonly BookingDBRepository _repository;

		public BookingDetailViewComponent(IRepository<Booking> repository)
		{
			_repository = (BookingDBRepository)repository;
		}

		public async Task<IViewComponentResult> InvokeAsync(BookingProcess data)
		{
			return View(data);
		}
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/ViewComponents/ConfirmationViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeestjeOpJeFeestje.Models;
using BeestjeOpJeFeestje.Models.Repositories;
using BeestjeOpJeFeestje.Models.Validators;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace BeestjeOpJeFeestje.ViewComponents
{
	public class ConfirmationViewComponent : ViewComponent
	{
		private readonly IRepository<Animal> _animalRepository;
		private readonly IRepository<Accessories> _accessoriesRepository;
		private readonly IRepository<ClientInfo> _clientInfoRepository;
		private readonly IRepository<BookingProcess> _bookingProcessRepository;
		private readonly IRepository<Booking> _bookingRepository;

		public ConfirmationViewComponent(IRepository<BookingProcess> bookingProcessRepository,
			IRepository<Booking> bookingRepository,
			IRepository<Animal> animalRepository,
			IRepository<Accessories> accessoriesRepository,
			IRepository<ClientInfo> clientInfoRepository)
		{
			_animalRepository = animalRepository;
			_accessoriesRepository = accessoriesRepository;
			_clientInfoRepository = clientInfoRepository;
			_bookingProcessRepository = bookingProcessRepository;
			_bookingRepository = bookingRepository;
		}

		public async Task<IViewComponentResult> InvokeAsync(BookingProcess data)
		{
			List<Animal> animals = await GetAnimals(data.Animals.Select(e => e.ID).ToArray());
			List<Accessories> accessories = new List<Accessories>();
			List<Discounts> discounts = new List<Discounts>();

			DiscountValidator discountValidator = new DiscountValidator();

            if (data.Accessories != null)
			{
				accessories = await GetAccessories(data.Accessories.Select(e => e.ID).ToArray());
			}

			data.Animals = animals;
			data.Accessories = accessories;

			#region Discount

			int totalDiscountPercentage = 0;
			if (discountValidator.HasThreeSameTypeAnimals(animals))
            {
                totalDiscountPercentage += 10;
				discounts.Add(new Discounts()
				{
					Name = "3 Types",
					Discount = 10
				});
			}

            int duckDiscount = discountValidator.ChanceOnDuckDiscount(animals);

			if (duckDiscount > 0)
			{
				totalDiscountPercentage += duckDiscount;
				discounts.Add(new Discounts()
					{
						Name = "Eend",
						Discount = duckDiscount
				}
				);
			}

            int dateDiscount = discountValidator.BookingIsMondayOrTuesday(data.Booking.Date);
			if (dateDiscount > 0)
			{
				totalDiscountPercentage += dateDiscount;
				discounts.Add(new Discounts()
				{
					Name = data.Booking.Date.DayOfWeek.ToString(),
					Discount = dateDiscount
				});
			}

			int alphabetDiscount = discountValidator.GetAlphabeticalDiscount(animals);
			if (alphabetDiscount > 0)
			{
				totalDiscountPercentage += alphabetDiscount;
				discounts.Add(new Discounts()
				{
					Name = "Alfabet",
					Discount = alphabetDiscount
				});
			}

			totalDiscountPercentage = discountValidator.GetMaximumPercentage(totalDiscountPercentage, 60);
			data.TotalDiscount = totalDiscountPercentage;

			#endregion

			#region TotalPrice

			double totalPrice = 0.0;
			foreach (Animal animal in animals)
			{
				totalPrice += animal.Price;
			}

			foreach (Accessories accessoriese in accessories)
			{
				totalPrice += accessoriese.Price;
			}

			totalPrice = totalPrice / 100 * (100 - totalDiscountPercentage);

			#endregion

			data.TotalPrice = totalPrice;
			data.TotalDiscount = totalDiscountPercentage;
			data.Discounts = discounts;

			#region SaveData

			await _clientInfoRepository.Create(data.ClientInfo);
			data.ClientInfoId = data.ClientInfo.ID;
			data.DateTime = data.Booking.Date;

			data.BookingProcessAnimals = new List<BookingProcessAnimal>();
			data.BookingProcessAccessories = new List<BookingProcessAccessories>();
			foreach (Animal animal in animals)
			{
				data.BookingProcessAnimals.Add(new BookingProcessAnimal()
				{
					BookingProcessId = data.ID,
					AnimalId = animal.ID
				});
			}

			foreach (Accessories a in accessories)
			{
				data.BookingProcessAccessories.Add(new BookingProcessAccessories()
				{
					BookingProcessId = data.ID,
					AccessoriesId = a.ID
				});
			}

			await _bookingProcessRepository.Create(data);
			#endregion

			return View(data);
		}

		

        private async Task<List<Accessories>> GetAccessories(params int[] accessoriesId)
		{
			List<Accessories> list = new List<Accessories>();
			List<Accessories> accessories = await _accessoriesRepository.Find(accessoriesId);

			foreach (Accessories a in accessories)
			{
				list.Add(a);
			}

			return list;
		}

        private async Task<List<Animal>> GetAnimals(params int[] animalId)
		{
			List<Animal> list = new List<Animal>();
			List<Animal> animals = await _animalRepository.Find(animalId);

			foreach (Animal animal in animals)
			{
				list.Add(animal);
			}

			return list;
		}
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/ViewComponents/PersonalInformationViewComponent.cs
using System.Threading.Tasks;
using BeestjeOpJeFeestje.Models;
using BeestjeOpJeFeestje.Models.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.ViewComponents
{
	public class PersonalInformationViewComponent : ViewComponent
	{
		private readonly BookingDBRepository _repository;

		public PersonalInformationViewComponent(IRepository<Booking> repository)
		{
			_repository = (BookingDBRepository)repository;
		}

		public async Task<IViewComponentResult> InvokeAsync(BookingProcess data)
		{
			return View(data);
		}
	}
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Bookings/AnimalSelection.cshtml
@model BeestjeOpJeFeestje.Models.BookingProcess

@{
    ViewData["Title"] = "Edit";
}

<h2>Booking</h2>
<hr/>
<div class="row">
    <div class="col col-9" style="padding: 0">
        @switch (Model.Booking.BookingState)
        {
            case BookingState.Animals:
                @if (TempData["error"] != null)
                {
                    <span class="text-danger">@TempData["error"]</span>
                }
                @await Component.InvokeAsync("AnimalSelection", @Model)
                break;
            case BookingState.Accessories:
                @await Component.InvokeAsync("AccessoriesSelection", @Model)
                break;
            case BookingState.Details:
                @await Component.InvokeAsync("PersonalInformation", @Model)
                break;
            case BookingState.Confirmation:
                @await Component.InvokeAsync("Confirmation", @Model)
                break;
        }
    </div>
    <div class="col col-3">
        @await Component.InvokeAsync("BookingDetail", @Model)
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Bookings/Delete.cshtml
@model BeestjeOpJeFeestje.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientInfo.Email)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Bookings/Details.cshtml
@model BeestjeOpJeFeestje.Models.Booking

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.Date)
            </div>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.TotalPrice)
            </div>
        </dd>
        <dt class="col-sm-2">
            Full Name
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.ClientInfo.FirstName)  @Html.DisplayFor(model => model.ClientInfo.LastName)
            </div>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientInfo.Email)
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.ClientInfo.Email)
            </div>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientInfo.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.ClientInfo.PhoneNumber)
            </div>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientInfo.Address)
        </dt>
        <dd class="col-sm-10">
            <div class="row">
                @Html.DisplayFor(model => model.ClientInfo.Address)
            </div>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BookingAnimals)
        </dt>
        <dd class="col-sm-10">
            @foreach (BookingAnimal ba in @Model.BookingAnimals)
            {
                <div class="row">
                    @ba.Animal.Name
                </div>
            }
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BookingAccessories)
        </dt>
        <dd class="col-sm-10">
            @foreach (BookingAccessories ba in @Model.BookingAccessories)
            {
                <div class="row">
                    @ba.Accessories.Name
                </div>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Bookings/Index.cshtml
@model IEnumerable<BeestjeOpJeFeestje.Models.Booking>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientInfo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Booking item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientInfo.FirstName)
                @Html.DisplayFor(modelItem => item.ClientInfo.LastName)
                <br/>
                @Html.DisplayFor(modelItem => item.ClientInfo.Address)
            </td>
            <td>
                <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-controller="Bookings" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>